version: '3'

services:
  react:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend/app

  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
