# Generated by Django 3.2 on 2023-05-12 14:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='/home/kali/Desktop/DIAM/FinalProject/sportsblog/blog/static'), upload_to='profile_pics'),
        ),
    ]
