# Generated by Django 3.2 on 2023-05-12 20:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', storage=django.core.files.storage.FileSystemStorage(location='/home/kali/Desktop/DIAM/FinalProject/sportsblog/backend/frontend/build/static'), upload_to='profile_pics'),
        ),
    ]
